/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DriverLog.java
 *
 * Created on 27/Nov/2011, 18:31:07
 */

package visual;

/**
 *
 * @author Babo
 */
public class DriverLog extends javax.swing.JFrame {
    
    public Object[][] driverBeliefs = new Object [][] {
        {"Posição", null},
        {"Acidentes Conhecidos", null},
        {"Tipo de rota", null},
        {"Destino", null},
        {"Última Mensagem Rádio", null}
    };
    
    /** Creates new form DriverLog */
    public DriverLog() {  
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        textArea1.setEditable(false);

        label1.setText("Log das ações do condutor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(driverBeliefs,
            new String [] {
                "Belief", "Valor"
            }));
            jScrollPane1.setViewportView(jTable1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            textArea1.getAccessibleContext().setAccessibleName("driverlog");
            textArea1.getAccessibleContext().setAccessibleDescription("driverlog");

            pack();
        }// </editor-fold>//GEN-END:initComponents


    public void changeText(String add)
    {
        textArea1.append(add + "\n");
        textArea1.setCaretPosition(textArea1.getText().length());
       this.repaint();
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

}
